# Generated by Django 3.1.14 on 2023-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ful_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('telegram', models.URLField(verbose_name='Your telegram profile')),
                ('instagram', models.URLField(blank=True, verbose_name='Your instagram profile')),
                ('github', models.URLField(verbose_name='Your GitHub profile')),
                ('email', models.URLField(verbose_name='Your Email')),
            ],
        ),
    ]
