# Generated by Django 3.1.14 on 2023-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
    ]
