# Generated by Django 4.1.7 on 2023-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammodel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
