# Generated by Django 4.2 on 2023-05-31 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='img')),
                ('text', models.TextField(max_length=1000)),
                ('datatime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='img')),
                ('text', models.TextField(max_length=1000)),
                ('img2', models.ImageField(upload_to='img')),
                ('img3', models.ImageField(blank=True, upload_to='img')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.newsmodel')),
            ],
        ),
    ]
