# Generated by Django 4.1.7 on 2023-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20230322_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
