# Generated by Django 4.1.7 on 2023-04-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
