# Generated by Django 4.1.7 on 2023-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('full_name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
