# Generated by Django 4.1.7 on 2023-04-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_teachermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
