# Generated by Django 4.1.5 on 2023-05-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_infomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
