# Generated by Django 4.1.7 on 2023-05-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_rename_full_name_contactmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoModel',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
        migrations.AddField(
            model_name='infomodell',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.teachermodell'),
        ),
    ]
