# Generated by Django 4.2.1 on 2023-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_infomodel_rename_teachermodell_teachermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='pdf')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='document',
        ),
    ]
