# Generated by Django 4.2.1 on 2023-05-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_infomodell_delete_documentmodel_delete_infomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='pdf')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('rate', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.teachermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoModell',
        ),
    ]
