# Generated by Django 4.2.1 on 2023-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_teachermodell_remove_documentmodel_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='pdf')),
                ('types', models.CharField(choices=[('word', '.docx'), ('pdf', '.pdf'), ('excel', '.xlsx'), ('powerpoint', '.pptx')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentModel',
        ),
        migrations.AlterField(
            model_name='teachermodell',
            name='teacher23',
            field=models.CharField(choices=[('katta', 'oqituvchi'), ('dotsent', 'dotsent'), ('professor', 'professor'), ('assistent', 'assistent')], max_length=214),
        ),
    ]
