# Generated by Django 4.2.1 on 2023-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_documentmodel_delete_documentmodell'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
