# Generated by Django 4.2.1 on 2023-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_documentmodel_time_alter_documentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='types',
            field=models.CharField(max_length=100),
        ),
    ]
