# Generated by Django 4.2.1 on 2023-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_alter_documentmodel_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('rate', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='pdf')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoModel',
        ),
    ]
